//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;

namespace DataLayer
{
    [AttributeUsage(AttributeTargets.Field | AttributeTargets.Property, AllowMultiple = false, Inherited = true)]
    public class DateValidatorDB : ValidationAttribute
    {

        private const string InvalidDate = "Please enter a valid date";

        private const string GreaterDate = "Your age should be greater than or equal to 18 years";

        protected override ValidationResult IsValid(object value, ValidationContext validationContext)
        {
            try
            {
                DateTime dateTime = Convert.ToDateTime(value);

                if (dateTime >= DateTime.Now.AddYears(-18))
                {
                    return new ValidationResult(GreaterDate);
                }

                return ValidationResult.Success;

            }
            catch
            {
                return new ValidationResult(InvalidDate);
            }
        }

    }
}