//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LeaveTransaction
    {
        [Display(Name = "Transaction ID")]
        public int TransactionId { get; set; }

        [Display(Name = "Employee ID")]
        public Nullable<int> EmployeeId { get; set; }

        [Display(Name = "Date of Request")]
        public System.DateTime DateOfRequest { get; set; }

        [Display(Name = "Start Date")]
        public System.DateTime StartDate { get; set; }

        [Display(Name = "End Date")]
        public System.DateTime EndDate { get; set; }

        [Display(Name = "No. of Days")]
        public int NoOfDays { get; set; }

        [Display(Name = "Transaction Status")]
        public string TransactionStatus { get; set; }

        [Display(Name = "Reason")]
        public string Reason { get; set; }
    
        public virtual EmployeeDetail EmployeeDetail { get; set; }
    }
}
