//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ProjectAttendance
    {
        [Display(Name = "Employee ID")]
        public int EmployeeId { get; set; }

        [Display(Name = "Project ID")]
        public int ProjectId { get; set; }

        [Display(Name = "Date Of Attendance")]
        public System.DateTime DateOfAttendance { get; set; }

        [Display(Name = "End Date")]
        public Nullable<System.DateTime> EndDate { get; set; }

        [Display(Name = "Attendance Status")]
        public Nullable<int> AttendanceStatus { get; set; }
    
        public virtual EmployeeDetail EmployeeDetail { get; set; }
        public virtual ProjectDetail ProjectDetail { get; set; }
    }
}
